### ISSUE TITLE
Player swap screen error

### ISSUE THREAD

**Issue by SamRod33** [SamRod33/UNO_Game#20]
`ocamlbuild -use-ocamlfind -tag 'debug' GUIMain.byte && OCAMLRUNPARAM=b ./GUIMain.byte
Finished, 37 targets (37 cached) in 00:00:00.
Fatal error: exception Failure("player not found")
Raised at Stdlib.failwith in file "stdlib.ml", line 29, characters 17-33
Called from Player.swap_hands in file "player.ml", line 18, characters 16-39
Called from State.swap_rotate_players in file "state.ml", line 120, characters 10-58
Called from State.play_card in file "state.ml", line 210, characters 20-56
Called from GUIMain.gui_player_play in file "GUIMain.ml", line 57, characters 8-26
Called from GUIMain in file "GUIMain.ml", line 123, characters 9-16
make: *** [Makefile:43: uno-gui] Error 2`

**Comment by keritenerowicz** [comment]
what commands did u use to get this?

**Comment by keritenerowicz** [comment]
![image](https://user-images.githubusercontent.com/46474707/119401475-89a94980-bca9-11eb-8685-3c3c6379536f.png)
the attempted swap id and id of player at index 0 (on the swap screen are the same - I believe the error is in another file, I will look around to find it
